---

# see https://deployn.de/blog/setup-calibre/#cwa-calibre-web-automated--der-moderne-fork

- name: Start Mediathekview
  block:
    - name: Create Mediathekview Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ mediathekview_data_directory }}/config"
        - "{{ mediathekview_data_directory }}/data"

    - name: Mediathekview Docker Container
      community.docker.docker_container:
        name: "{{ mediathekview_container_name }}"
        image: conrad784/mediathekview-webinterface:latest
        pull: true
        volumes:
          - "{{ mediathekview_data_directory }}/config:/config"
          - "{{ mediathekview_tv_root }}:/tv"
          - "{{ mediathekview_data_directory }}/data:/data"
        env:
          TZ: "{{ ansible_nas_timezone }}"
          PUID: "{{ mediathekview_user_id }}"
          PGID: "{{ mediathekview_group_id }}"
        ports:
          - "{{ mediathekview_port }}:8084"
        restart_policy: unless-stopped
        memory: "{{ mediathekview_memory }}"
        labels:
          traefik.enable: "{{ mediathekview_available_externally | string }}"
          traefik.http.routers.mediathekview.rule: "Host(`{{ mediathekview_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.mediathekview.tls.certresolver: "letsencrypt"
          traefik.http.routers.mediathekview.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.mediathekview.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.services.mediathekview.loadbalancer.server.port: "5800"
  when: mediathekview_enabled is true

- name: Stop Mediathekview
  block:
    - name: Stop Mediathekview
      community.docker.docker_container:
        name: "{{ mediathekview_container_name }}"
        state: absent
  when: mediathekview_enabled is false
