---
- name: Start dupeGuru
  block:
    - name: Create dupeGuru Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ dupeguru_config_directory }}"
        - "{{ dupeguru_storage_directory }}"
        - "{{ dupeguru_trash_directory }}"

    - name: dupeGuru Docker Container
      community.docker.docker_container:
        name: "{{ dupeguru_container_name }}"
        image: jlesage/dupeguru
        pull: true
        volumes:
          - "{{ dupeguru_config_directory }}:/config:rw"
          - "{{ dupeguru_storage_directory }}:/storage:rw"
          - "{{ dupeguru_trash_directory }}:/trash:rw"
        ports:
          - "{{ dupeguru_web_port }}:5801"
        env:
          TZ: "Europe/Berlin"
          WEB_FILE_MANAGER: "1"
          DARK_MODE: "1"
          LANG: "de_DE:UTF-8"
          WEB_LISTENING_PORT: "5801"
          VNC_LISTENING_PORT: "5901"
        restart_policy: unless-stopped
        memory: "{{ dupeguru_memory }}"
  when: dupeguru_enabled is true

- name: Stop dupeGuru
  block:
    - name: Stop dupeGuru
      community.docker.docker_container:
        name: "{{ dupeguru_container_name }}"
        state: absent
  when: dupeguru_enabled is false
