---
##                       ._____.   .__
##  _____    ____   _____|__\_ |__ |  |   ____             ____ _____    ______
##  \__  \  /    \ /  ___/  || __ \|  | _/ __ \   ______  /    \\__  \  /  ___/
##   / __ \|   |  \\___ \|  || \_\ \  |_\  ___/  /_____/ |   |  \/ __ \_\___ \
##  (____  /___|  /____  >__||___  /____/\___  >         |___|  (____  /____  >
##       \/     \/     \/        \/          \/               \/     \/     \/
##     a n s i b l e - n a s      https://github.com/davestephens/ansible-nas

# Add your all.yml config overrides to this file. See group_vars/all.yml for all possible settings.

# Example options
ansible_nas_hostname: RaspiNAS
ansible_nas_timezone: Europe/Berlin

## Enable some applications
homepage_enabled: true

## Content Management
dokuwiki_enabled: true
freshrss_enabled: true

## Media Serving
calibre_enabled: true
calibre_cwa_enabled: true
calibreweb_enabled: true
jdownloader2_enabled: true
lychee_enabled: true
mediathekview_enabled: true
pyload_enabled: true
vlc_enabled: tru

## Monitoring
glances_enabled: true
wireshark_enabled: true

## Home Automation
homeassistant_enabled: true
homeassistant_available_externally: true
mosquitto_enabled: true

## System Tools
portainer_enabled: true
dupeguru_enabled: true
duplicati_enabled: true
