---
- name: Start jdownloader
  block:
    - name: Create jdownloader Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - "{{ jdownloader_data_directory }}/data"

    - name: jdownloader Docker Container
      community.docker.docker_container:
        name: "{{ jdownloader_container_name }}"
        image: jlesage/jdownloader
        # pull: missing
        state: started
        volumes:
          - "{{ jdownloader_data_directory }}/data:/config:rw"
          - "{{ jdownloader_download_directory }}:/output:rw"
        env:
          TZ: "{{ ansible_nas_timezone }}"
          PUID: "{{ jdownloader_user_id }}"
          PGID: "{{ jdownloader_group_id }}"
          PASSWORD: "{{ jdownloader_password }}"
          CLI_ARGS: "{{ jdownloader_cli_args }}"
        ports:
          - "{{ jdownloader_port }}:5800"
        security_opts: "{{ jdownloader_security_opts }}"
        restart_policy: unless-stopped
        memory: "{{ jdownloader_memory }}"
  when: jdownloader_enabled is true

- name: Stop jdownloader
  block:
    - name: Stop jdownloader
      community.docker.docker_container:
        name: "{{ jdownloader_container_name }}"
        state: absent
  when: jdownloader_enabled is false
